apiVersion: apps/v1
kind: Deployment
metadata: 
  name: customerservice-deployment
  namespace: default
  labels: 
    app: customerservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customerservice
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: customerservice
    spec:
      containers:
        - name: customerservice-container
          image: >-
            sibendu/customerservice
          ports:
            - containerPort: 8080
              protocol: TCP                
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata: 
  name: customerservice-service
  namespace: default
  labels: 
    app: customerservice
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080 		
  selector:
    app: customerservice
